import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#0e1321",
        "surface-dim": "#0e1321",
        "surface-bright": "#343948",
        "surface-container-lowest": "#090e1c",
        "surface-container-low": "#161b2a",
        "surface-container": "#1a1f2e",
        "surface-container-high": "#252a39",
        "surface-container-highest": "#303444",
        "on-surface": "#dee2f6",
        "on-surface-variant": "#bbcabf",
        "inverse-surface": "#dee2f6",
        "inverse-on-surface": "#2b303f",
        "outline": "#86948a",
        "outline-variant": "#3c4a42",
        "surface-tint": "#4edea3",
        "primary": "#4edea3",
        "on-primary": "#003824",
        "primary-container": "#10b981",
        "on-primary-container": "#00422b",
        "inverse-primary": "#006c49",
        "secondary": "#5de6ff",
        "on-secondary": "#00363e",
        "secondary-container": "#00cbe6",
        "on-secondary-container": "#00515d",
        "tertiary": "#ffafd3",
        "on-tertiary": "#620040",
        "tertiary-container": "#f876ba",
        "on-tertiary-container": "#72004b",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        "secondary-fixed": "#a2eeff",
        "secondary-fixed-dim": "#2fd9f4",
        "on-secondary-fixed": "#001f25",
        "on-secondary-fixed-variant": "#004e5a",
        "tertiary-fixed": "#ffd8e7",
        "tertiary-fixed-dim": "#ffafd3",
        "on-tertiary-fixed": "#3d0026",
        "on-tertiary-fixed-variant": "#85145a",
        "background": "#0e1321",
        "on-background": "#dee2f6",
        "surface-variant": "#303444",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter": "1.5rem",
        "container-padding-desktop": "2.5rem",
        "stack-md": "1rem",
        "container-padding-mobile": "1.25rem",
        "unit": "4px",
        "stack-sm": "0.5rem",
        "stack-lg": "2rem",
      },
      fontFamily: {
        "headline-lg": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "title-md": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
